---
title: "HeartDisease"
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2)

heart_disease <- read_csv("heart_disease_patients.csv")
```


2. Quantifying patient differences
```{r}
# Evidence that the data should be scaled?
summary(heart_disease)

# Remove id
heart_disease <- heart_disease[, !(names(heart_disease) %in% c("id"))]

# Scaling data and saving as a data frame
scaled <- scale(heart_disease)

# Let's see the data after we scaled it
summary(scaled)
```

3. Let's start grouping patients
```{r}
# Set the seed so that results are reproducible
set.seed(10)

# Select a number of clusters
k <- 5

# Run the k-means algorithm
first_clust <- kmeans(scaled, centers = k, nstart = 1)

# How many patients are in each cluster?
first_clust$size
```

4. Another round of k-means
```{r}
# Set the seed
set.seed(38)

# Select a number of clusters and runt the k-means algorithm
k <- 5
second_clust <- kmeans(scaled, centers = k, nstart = 1)

# How many patients are in each cluster?
second_clust$size
```

5. Comparing patient clusters
```{r}
# Add cluster assignments to the data
heart_disease["first_clust"] <- first_clust$cluster
heart_disease["second_clust"] <- second_clust$cluster

# Create and print the plot of age and chol for the first clustering algorithm
plot_one <- ggplot(heart_disease, aes(x=age, y=chol, color=as.factor(first_clust))) +
  geom_point()
plot_one

# Create and print the plot of age and chol for the second clustering algorithm
plot_two <- ggplot(heart_disease, aes(x=age, y=chol, color=as.factor(second_clust))) + 
  geom_point()
plot_two
```

6. Hierarchical clustering: another clustering approach
```{r}
# Execute hierarchical clustering with complete linkage
hier_clust_1 <- hclust(dist(scaled), method = "complete")

# Print the dendogram
plot(hier_clust_1)

# Get cluster assignments based on number os selecter cluster
hc_1_assign <- cutree(hier_clust_1, 5)
```

7. Hierarchical clustering round two
```{r}
# Execute hierarchical clustering with single linkagw
hier_clust_2 <- hclust(dist(scaled), method = "single")

# Print the dendogram
plot(hier_clust_2)

# Get cluster assignments based on number of selected clusters
hc_2_assign <- cutree(hier_clust_2, 5)
```

8. Comparing clustering results
```{r}
# Add assignment of chosen hierarchical linkage
heart_disease["hc_clust"] <- hc_1_assign

# Remove the sex, first_clust, and second_clust variables
hd_simple <- heart_disease[, ! (names(heart_disease) %in% c("sex", "first_clust", "second_clust"))]

# Get the mean and standard deviation summary statistics
clust_summary <- do.call(data.frame, aggregate(. ~hc_clust, data = hd_simple, function(x)c (avg  = mean(x), sd = sd(x))))
clust_summary
```

9. Visualizing the cluster contents
```{r}
# Plot age and chol
plot_one <- ggplot(heart_disease, aes(x=age, y = chol, color =as.factor(hc_clust))) + geom_point() + labs(title = "Age vs Serum Cholestoral")
plot_one

# Plot oldpeak and trestbps
plot_two <- ggplot(heart_disease, aes(x = oldpeak, y = trestbps, color = as.factor(hc_clust))) + geom_point() + labs(title = "ST Depression vs Resting Blood Pressure")
plot_two
```

10. Conclusion
```{r}
# Add TRUE if the algorithm shows promise, add FALSE if it does not
explore_kmeans <- FALSE
explore_hierarch_complete <- TRUE
explore_hierarch_single <- FALSE
```

